"""Initial migration.

Revision ID: 3ea33eee1690
Revises: 
Create Date: 2024-03-28 16:08:40.210599

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3ea33eee1690'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('todo_table')
    with op.batch_alter_table('user_table', schema=None) as batch_op:
        batch_op.drop_index('ix_user_table_email')
        batch_op.drop_index('ix_user_table_username')

    op.drop_table('user_table')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_table',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('username', sa.VARCHAR(length=64), nullable=True),
    sa.Column('email', sa.VARCHAR(length=120), nullable=True),
    sa.Column('password_hash', sa.VARCHAR(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user_table', schema=None) as batch_op:
        batch_op.create_index('ix_user_table_username', ['username'], unique=1)
        batch_op.create_index('ix_user_table_email', ['email'], unique=1)

    op.create_table('todo_table',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('task', sa.VARCHAR(length=150), nullable=True),
    sa.Column('completed', sa.BOOLEAN(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
